apiVersion: v1
kind: Pod
metadata:
name: busybox
namespace: default
spec:
containers:
- image: registry.in.dataengine.com/library/busybox:1.25
command:
  - sleep
  - "3600"
imagePullPolicy: IfNotPresent
name: busybox
restartPolicy: Always